import type { GameType } from '@/src/types';

export interface GameInstruction {
  title: string;
  emoji: string;
  description: string;
  instructions: string[];
}

export const gameInstructions: Record<NonNullable<GameType>, GameInstruction> = {
  'number-guess': {
    title: 'Number Guess',
    emoji: '🎯',
    description: 'Guess the number within your chosen range! Get helpful hints to find the answer.',
    instructions: [
      'Set your minimum and maximum number range',
      'Click "Start Guessing!" to begin',
      'Enter your guess in the input field',
      'Read the hints - they tell you if you\'re too high or too low',
      'The range narrows after each guess to help you focus',
      'Keep guessing until you find the number!',
    ],
  },
  'rock-paper-scissors': {
    title: 'Rock Paper Scissors',
    emoji: '✂️',
    description: 'Classic RPS against the computer! Play best-of-3 or best-of-5 matches.',
    instructions: [
      'Choose Rock, Paper, or Scissors',
      'The computer will make its choice',
      'Rock beats Scissors, Scissors beats Paper, Paper beats Rock',
      'First to win 2 rounds (best-of-3) or 3 rounds (best-of-5) wins!',
      'Click your choice before the timer runs out',
    ],
  },
  'quick-math-duel': {
    title: 'Quick Math Duel',
    emoji: '⚡',
    description: 'Race against time to solve arithmetic problems! Addition, subtraction, multiplication, and comparisons.',
    instructions: [
      'You\'ll see math problems for 2-3 seconds each',
      'Solve addition, subtraction, or multiplication quickly',
      'Or answer "which is bigger?" comparison questions',
      'Type your answer before time runs out',
      'Score points for correct answers!',
    ],
  },
  'typing-burst': {
    title: 'Typing Burst',
    emoji: '⌨️',
    description: 'Test your typing speed! Type random words or code-style identifiers as fast as you can.',
    instructions: [
      'Words or code identifiers will appear on screen',
      'Type each word exactly as shown',
      'Press Enter or Space after each word',
      'Your WPM (Words Per Minute) and accuracy are tracked',
      'Try to beat your best score!',
    ],
  },
  'odd-one-out': {
    title: 'Odd One Out',
    emoji: '🔍',
    description: 'Find the word that doesn\'t belong! 3 words share a category, 1 is different.',
    instructions: [
      'Four words will be displayed',
      'Three words belong to the same category (e.g., animals)',
      'One word is the "odd one out"',
      'Click on the word that doesn\'t belong',
      'Get points for correct answers!',
    ],
  },
  'memory-flip': {
    title: 'Memory Flip',
    emoji: '🃏',
    description: 'Match pairs of cards! Flip two cards at a time to find matching pairs.',
    instructions: [
      'You\'ll see 8-10 cards (4-5 pairs) face down',
      'Click a card to flip it over',
      'Click another card to find its match',
      'If they match, they stay face up',
      'If they don\'t match, they flip back',
      'Match all pairs to win!',
    ],
  },
  'quick-word-chain': {
    title: 'Quick Word Chain',
    emoji: '🔗',
    description: 'Build a word chain! Type a related word to continue the chain before time runs out.',
    instructions: [
      'A starting word is shown',
      'Type a word related to it (synonym, antonym, or association)',
      'You have a few seconds to respond',
      'The chain continues with your word',
      'Keep the chain going as long as possible!',
    ],
  },
  'simon-says': {
    title: 'Simon Says',
    emoji: '🎨',
    description: 'Repeat the pattern! Colored buttons light up in sequence - can you remember?',
    instructions: [
      'Watch as colored buttons light up in a pattern',
      'Remember the sequence',
      'Click the buttons in the same order',
      'The pattern gets longer each level',
      'Make a mistake and the game ends',
    ],
  },
  'slide-puzzle-2048': {
    title: '2048 Slide Puzzle',
    emoji: '🧩',
    description: 'Merge tiles to reach 2048! Slide tiles in four directions to combine matching numbers.',
    instructions: [
      'Use arrow keys or swipe to move tiles',
      'When two tiles with the same number touch, they merge',
      'Keep merging to create higher numbers',
      'Try to reach 2048!',
      'Game ends when the board is full and no moves are possible',
    ],
  },
  'snake-avoider': {
    title: 'Snake / Avoider',
    emoji: '🐍',
    description: 'Control a snake or avoid obstacles! Navigate for 60-90 seconds without crashing.',
    instructions: [
      'Use arrow keys to move',
      'Snake: Eat food to grow, avoid walls and yourself',
      'Avoider: Avoid falling obstacles',
      'Survive for 60-90 seconds',
      'Score points for food eaten or time survived',
    ],
  },
  'little-alchemy': {
    title: 'Little Alchemy',
    emoji: '⚗️',
    description: 'Combine elements to discover new items! Start with fire, water, earth, and air.',
    instructions: [
      'Start with base elements: fire, water, earth, air',
      'Drag and drop elements together to combine them',
      'Discover new items through combinations',
      'Build your discovery list',
      'Try different combinations to find all items!',
    ],
  },
  'word-scramble': {
    title: 'Word Scramble',
    emoji: '🔤',
    description: 'Unscramble the word before time runs out! Choose from categories like tech, school, or fruits.',
    instructions: [
      'A scrambled word is displayed',
      'Unscramble the letters to form the correct word',
      'Type your answer in the input field',
      'You have limited time to solve it',
      'Choose different categories for variety',
    ],
  },
  'trivia-quiz': {
    title: 'Quick Trivia Quiz',
    emoji: '🧠',
    description: 'Answer 5-10 questions per session! General knowledge, tech facts, and brain teasers.',
    instructions: [
      'Read each question carefully',
      'Select your answer from multiple choices',
      'Get immediate feedback on your answer',
      'Score points for correct answers',
      'Complete 5-10 questions per session',
    ],
  },
  'doodle-challenge': {
    title: 'Doodle Challenge',
    emoji: '✏️',
    description: 'Draw based on a random prompt! Create art for 60-120 seconds on a digital canvas.',
    instructions: [
      'A random drawing prompt appears',
      'Use your mouse or touch to draw on the canvas',
      'Draw for 60-120 seconds',
      'Express your creativity!',
      'Optionally save or share your creation',
    ],
  },
  'spot-difference': {
    title: 'Spot the Difference',
    emoji: '👁️',
    description: 'Find 3-5 differences between two images! Click on the differences you spot.',
    instructions: [
      'Two similar images are displayed side by side',
      'Look carefully for differences',
      'Click on each difference you find',
      'Find all 3-5 differences to complete the challenge',
      'Take your time and look closely!',
    ],
  },
  'paper-airplane': {
    title: 'Paper Airplane Sim',
    emoji: '✈️',
    description: 'Adjust parameters and throw a plane! Try to beat your distance record.',
    instructions: [
      'Adjust 2-3 parameters: angle, power, and wind',
      'Click "Throw" to launch your plane',
      'Watch it fly and see how far it goes',
      'Try different combinations to beat your best distance',
      'Experiment with different settings!',
    ],
  },
  'light-logic': {
    title: 'Light Logic Puzzles',
    emoji: '💡',
    description: 'Solve mini Sudoku, Nonograms, or grid puzzles! Perfect for quick brain workouts.',
    instructions: [
      'Mini Sudoku: Fill 4×4 or 6×6 grids with numbers',
      'Nonograms: Use clues to fill pixel grids',
      'Follow the rules and constraints',
      'Complete the puzzle to win',
      'Start with easy puzzles and work your way up',
    ],
  },
  'story-chain': {
    title: 'Story Chain',
    emoji: '📖',
    description: 'Build a silly story together! Add 3-5 sentences to continue the story.',
    instructions: [
      'Read the first sentence provided',
      'Add 3-5 short sentences to continue the story',
      'Be creative and have fun!',
      'Build on what came before',
      'Create a complete, silly story together',
    ],
  },
  'code-puzzles': {
    title: 'Code Puzzles',
    emoji: '💻',
    description: 'Find bugs or predict output! Language-neutral code logic puzzles.',
    instructions: [
      'Find the bug: Look for errors in code snippets',
      'Predict output: Determine what code will output',
      'No real code execution - just logic thinking',
      'Select your answer from options',
      'Learn programming logic while having fun!',
    ],
  },
  'tetris-blocks': {
    title: 'Falling Blocks',
    emoji: '🧱',
    description: 'Classic falling blocks puzzle! Keep speed low with 3 lives or 5 levels max.',
    instructions: [
      'Use arrow keys to move and rotate blocks',
      'Clear lines by filling rows completely',
      'Blocks fall slowly - take your time',
      'You have 3 lives or 5 levels to complete',
      'Score points for each line cleared',
    ],
  },
  'minute-win-it': {
    title: 'Minute to Win It',
    emoji: '⏱️',
    description: 'Fast clickable timing challenges! Digital versions of physical office games.',
    instructions: [
      'Complete quick challenges in under a minute',
      'Stack virtual cups, click moving targets, etc.',
      'Follow on-screen instructions',
      'Use your mouse or touch to interact',
      'Beat the timer to win!',
    ],
  },
  'physical-challenge': {
    title: 'Physical Challenge',
    emoji: '🏃',
    description: 'Get moving! Physical activities like jumping jacks, stretches, or walking.',
    instructions: [
      'Follow on-screen instructions for physical activities',
      'Examples: 20 jumping jacks, desk yoga, walk 100 steps',
      'Complete the activity, then press "Done"',
      'Take a break from screen time',
      'Refresh your body and mind!',
    ],
  },
  // Existing games
  'mind-maze': {
    title: 'Mind Maze',
    emoji: '🧩',
    description: 'Navigate through mazes to sharpen spatial reasoning!',
    instructions: [
      'Find the path from start to end',
      'Use arrow keys or click buttons to move',
      'Navigate through 3 levels of increasing difficulty',
      'Avoid dead ends and find the exit',
    ],
  },
  'speed-match': {
    title: 'Speed Match',
    emoji: '⚡',
    description: 'Match patterns quickly to boost reaction time!',
    instructions: [
      'Match shapes and colors as fast as you can',
      'You have 5 seconds per round',
      'Complete 10 rounds',
      'Score points for speed and accuracy',
    ],
  },
  'logic-lock': {
    title: 'Logic Lock',
    emoji: '🔐',
    description: 'Solve logic puzzles to unlock your thinking!',
    instructions: [
      'Read each logic puzzle carefully',
      'Select your answer from multiple choices',
      'Complete 5 puzzles with explanations',
      'Score tracking shows your progress',
    ],
  },
  'chess-puzzle': {
    title: 'Chess Puzzle',
    emoji: '♟️',
    description: 'Master tactical chess puzzles for strategic thinking!',
    instructions: [
      'Find the best move in each position',
      'Multiple difficulty levels available',
      'Hints are available if you need help',
      'Think strategically!',
    ],
  },
  'sudoku': {
    title: 'Sudoku',
    emoji: '🔢',
    description: 'Fill the grid with numbers for perfect focus!',
    instructions: [
      'Fill the 9×9 grid with numbers 1-9',
      'Each row, column, and 3×3 box must contain all digits',
      '3 difficulty levels available',
      'Real-time error tracking helps you learn',
    ],
  },
  'brain-teaser': {
    title: 'Brain Teaser',
    emoji: '🧠',
    description: 'Challenge your mind with tricky brain puzzles!',
    instructions: [
      'Solve logic puzzles and riddles',
      'Multiple choice questions with explanations',
      'Complete 5 teasers',
      'Think outside the box!',
    ],
  },
  'number-crunch': {
    title: 'Number Crunch',
    emoji: '🔢',
    description: 'Select numbers that sum to the target!',
    instructions: [
      'Find combinations of numbers that add up to the target',
      'Click numbers to select them',
      'Time pressure adds excitement',
      'Complete 10 rounds',
    ],
  },
  'word-chain': {
    title: 'Word Chain',
    emoji: '🔗',
    description: 'Continue word chains - each word starts with last letter!',
    instructions: [
      'Build word sequences',
      'Each new word must start with the last letter of the previous word',
      'Complete 15 rounds',
      'Score tracking shows your progress',
    ],
  },
  'pattern-master': {
    title: 'Pattern Master',
    emoji: '🎨',
    description: 'Remember and repeat color patterns!',
    instructions: [
      'Watch the color sequence carefully',
      'Click colors in the same order',
      '10 levels of increasing difficulty',
      'Visual pattern matching challenge',
    ],
  },
  'memory-matrix': {
    title: 'Memory Matrix',
    emoji: '🧠',
    description: 'Memorize highlighted cells in the grid!',
    instructions: [
      'Remember which cells are highlighted',
      'Click the cells you remember',
      '8 levels to complete',
      'Visual memory training',
    ],
  },
  'quick-draw': {
    title: 'Quick Draw',
    emoji: '⚡',
    description: 'Quickly select the correct shape!',
    instructions: [
      'Fast shape recognition challenge',
      'Complete 15 rounds',
      'Time pressure keeps it exciting',
      'Score points for speed',
    ],
  },
  'color-blast': {
    title: 'Color Blast',
    emoji: '🎨',
    description: 'Select the target color quickly!',
    instructions: [
      'Color recognition challenge',
      'Complete 12 rounds',
      'Fast-paced gameplay',
      'Improve your color perception',
    ],
  },
  'sequence-solver': {
    title: 'Sequence Solver',
    emoji: '🔢',
    description: 'Find patterns in number sequences!',
    instructions: [
      'Look for arithmetic or geometric patterns',
      'Figure out what number comes next',
      'Complete 10 rounds',
      'Pattern recognition skills',
    ],
  },
  'word-search': {
    title: 'Word Search',
    emoji: '🔍',
    description: 'Find hidden words in the grid!',
    instructions: [
      'Search for words horizontally, vertically, or diagonally',
      'Click and drag to select words',
      'Find all words to complete',
      'Words can be forwards or backwards',
    ],
  },
  'code-breaker': {
    title: 'Code Breaker',
    emoji: '🔐',
    description: 'Crack the 4-digit code!',
    instructions: [
      'Guess the 4-digit code',
      'Get feedback on correct digits and positions',
      'Use logic to narrow down possibilities',
      'Crack the code in as few tries as possible',
    ],
  },
  'spot-the-diff': {
    title: 'Spot The Difference',
    emoji: '👁️',
    description: 'Find differences between two grids!',
    instructions: [
      'Compare two similar grids',
      'Click on the differences you find',
      'Find all differences to win',
      'Take your time and look carefully',
    ],
  },
  'block-puzzle': {
    title: 'Block Puzzle',
    emoji: '🧩',
    description: 'Combine blocks to reach higher numbers!',
    instructions: [
      'Drag and drop blocks onto the board',
      'Combine blocks to create higher numbers',
      'Clear lines to make space',
      'Reach the target score!',
    ],
  },
  'anagram-solver': {
    title: 'Anagram Solver',
    emoji: '🔤',
    description: 'Unscramble letters to form words!',
    instructions: [
      'Rearrange the letters to form a word',
      'Type your answer',
      'Get hints if you need help',
      'Score points for correct answers',
    ],
  },
  'math-rush': {
    title: 'Math Rush',
    emoji: '⚡',
    description: 'Solve math problems as fast as you can!',
    instructions: [
      'Solve addition, subtraction, and multiplication problems',
      '30-second timer adds pressure',
      'Score tracking shows your progress',
      'Beat your best time!',
    ],
  },
  'shape-shift': {
    title: 'Shape Shift',
    emoji: '🔄',
    description: 'Quickly select the correct shape!',
    instructions: [
      'Identify the correct shape quickly',
      'Complete rounds as fast as possible',
      'Score points for speed and accuracy',
      'Improve your visual recognition',
    ],
  },
  'fizzbuzz-mini': {
    title: 'FizzBuzz Mini',
    emoji: '🔢',
    description: 'Write a function to replace multiples of 3/5 with Fizz/Buzz',
    instructions: [
      'Write a function called fizzBuzz(n) that takes a number',
      'If n is divisible by 15, return "FizzBuzz"',
      'If n is divisible by 3, return "Fizz"',
      'If n is divisible by 5, return "Buzz"',
      'Otherwise, return the number as a string',
      'Test your function with numbers 1-50',
    ],
  },
  'code-golf-basics': {
    title: 'Code Golf Basics',
    emoji: '⛳',
    description: 'Shorten code snippets to fewest characters possible',
    instructions: [
      'You\'ll be given coding challenges like "reverse a string"',
      'Write the shortest code possible to solve the challenge',
      'Your score is based on code length - shorter is better!',
      'Complete all challenges to finish the game',
      'Remove unnecessary spaces and use concise syntax',
    ],
  },
  'predict-output': {
    title: 'Predict Output',
    emoji: '🔮',
    description: 'Guess the console output of JavaScript snippets',
    instructions: [
      'You\'ll see JavaScript code snippets',
      'Predict what will be logged to the console',
      'Choose from multiple choice options',
      'Test your understanding of JS behavior',
      'Complete all 5 questions to finish',
    ],
  },
  'golf-score': {
    title: 'Golf Score',
    emoji: '⛳',
    description: 'Calculate golf scores based on par and strokes',
    instructions: [
      'Write a function golfScore(par, strokes)',
      'Return "Hole-in-one!" if strokes === 1',
      'Return "Eagle" if strokes <= par - 2',
      'Return "Birdie" if strokes === par - 1',
      'Return "Par" if strokes === par',
      'Return "Bogey" if strokes === par + 1',
      'Return "Double Bogey" if strokes === par + 2',
      'Return "Go Home!" if strokes >= par + 3',
    ],
  },
  'elevator-saga': {
    title: 'Elevator Saga',
    emoji: '🏢',
    description: 'Control elevators to optimize movement in a 3-floor building',
    instructions: [
      'You control 2 elevators in a 3-floor building',
      'Use arrow buttons to move elevators up/down',
      'Click "Pick" to pick up waiting passengers',
      'Click "Drop" to drop off passengers',
      'Optimize movement to transport all passengers',
      'Score points for each passenger transported',
    ],
  },
  'sql-murder-mystery': {
    title: 'SQL Murder Mystery',
    emoji: '🔍',
    description: 'Solve a mystery by selecting the correct people from the database',
    instructions: [
      'You\'ll see a database of people with their details',
      'Read each question carefully',
      'Click on the people that match the criteria',
      'Select all correct answers and click "Check Answer"',
      'Solve all questions to complete the mystery',
    ],
  },
  'mini-code-combat': {
    title: 'Mini Code Combat',
    emoji: '⚔️',
    description: 'Navigate through mazes using arrow buttons',
    instructions: [
      'You\'ll see a maze grid with a start (🏁) and end (🎯)',
      'Use the arrow buttons (↑ ↓ ← →) to move your character',
      'Navigate from the green start to the red end',
      'Avoid walls (🧱) and stay on the path',
      'Complete all mazes to finish the game',
    ],
  },
  'leetcode-bites': {
    title: 'LeetCode Easy Bites',
    emoji: '💻',
    description: 'Solve 1-2 array/string problems with JS editor and tester',
    instructions: [
      'You\'ll get classic coding problems like "Two Sum"',
      'Write your solution in the code editor',
      'Use the test button to run your code',
      'Make sure all test cases pass',
      'Problems are simplified versions of LeetCode easy',
    ],
  },
  'checkio-missions': {
    title: 'CheckiO Missions',
    emoji: '🏝️',
    description: 'Solve Python/JS challenges like sorting numbers or finding median',
    instructions: [
      'Complete coding missions on different "islands"',
      'Each mission has a specific task (e.g., sort numbers)',
      'Write your solution and submit it',
      'Pass all test cases to complete the mission',
      'Move to the next mission after completion',
    ],
  },
  'codingame-clones': {
    title: 'CodinGame Clones',
    emoji: '🎮',
    description: 'Play interactive Tic-Tac-Toe against AI or with a friend',
    instructions: [
      'Choose to play vs AI or two-player mode',
      'Click on any empty square to place your mark',
      'Get three in a row (horizontal, vertical, or diagonal) to win',
      'First to win 3 games wins the match',
      'Have fun playing!',
    ],
  },
  'tic-tac-toe': {
    title: 'Tic-Tac-Toe',
    emoji: '⭕',
    description: 'Classic Tic-Tac-Toe game - play vs AI or two players',
    instructions: [
      'Choose to play vs AI or two-player mode',
      'Click on any empty square to place your mark (X or O)',
      'Get three in a row (horizontal, vertical, or diagonal) to win',
      'First to win 3 games wins the match',
      'Try to block your opponent while creating your own winning line!',
    ],
  },
  'chess': {
    title: 'Chess',
    emoji: '♟️',
    description: 'Play full chess game - two players on interactive board',
    instructions: [
      'Click on a piece to select it (highlighted in blue)',
      'Click on a valid square to move the piece',
      'Valid moves are highlighted in green',
      'Capture the opponent\'s king to win the game',
      'White moves first, then players alternate turns',
      'Captured pieces are shown on the sides of the board',
    ],
  },
};

export function getGameInstruction(gameType: GameType): GameInstruction | null {
  if (!gameType) return null;
  return gameInstructions[gameType] || null;
}

